import { estimateCost } from './calculations.mjs'
const el=(tag,text,attrs={})=>{const n=document.createElement(tag);if(text!==null&&text!==undefined)n.textContent=text;Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));return n}
const paragraph=(text,cls)=>el('p',text,cls?{class:cls}:{})
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:3,maximumFractionDigits:3}).format(n)
const number=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n)
const menu=document.querySelector('.research-menu')
document.addEventListener('click',e=>{if(menu&&!menu.contains(e.target))menu.open=false})
menu?.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.open=false;menu.querySelector('summary').focus()}})
if(location.pathname.includes('/research/'))document.querySelectorAll('[data-guide]').forEach(a=>{if(a.dataset.guide!=='honeyquest')a.href='../'+a.dataset.guide+'/'})
document.querySelectorAll('.contents a').forEach(a=>a.addEventListener('click',()=>{const target=document.getElementById(a.hash.slice(1));if(target){target.setAttribute('tabindex','-1');target.focus({preventScroll:true})}}))
function tabs(root,data,kind){
 const controls=el('div',null,{class:'controls',role:kind==='openness'?'tablist':'group','aria-label':kind==='openness'?'Model access types':'Software lifecycle stages'})
 const panel=el('div',null,{class:'panel',id:`panel-${kind}`,'aria-live':'polite'});if(kind==='openness')panel.setAttribute('role','tabpanel')
 const buttons=data.items.map((item,i)=>{const b=el('button',item.label,{type:'button',id:`${kind}-${i}`,'aria-controls':panel.id});if(kind==='openness')b.setAttribute('role','tab');controls.append(b);return b})
 function show(i){buttons.forEach((b,k)=>{b.setAttribute(kind==='openness'?'aria-selected':'aria-pressed',String(k===i));if(kind==='openness')b.tabIndex=k===i?0:-1});panel.replaceChildren();const item=data.items[i];panel.append(el('h4',item.title),paragraph(item.text));panel.setAttribute('aria-labelledby',buttons[i].id)
 if(item.example)panel.append(paragraph('Example: '+item.example));if(item.evidence)panel.append(paragraph('What a team can show: '+item.evidence));
 if(item.layers){const list=el('dl',null,{class:'glossary'});item.layers.forEach(row=>{const d=el('div');d.append(el('dt',row.name+' — '+row.state),el('dd',row.explanation));list.append(d)});panel.append(list)}
 }
 buttons.forEach((b,i)=>{b.addEventListener('click',()=>show(i));b.addEventListener('keydown',e=>{if(kind!=='openness')return;let next;if(e.key==='ArrowRight')next=(i+1)%buttons.length;else if(e.key==='ArrowLeft')next=(i-1+buttons.length)%buttons.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=buttons.length-1;if(next!==undefined){e.preventDefault();show(next);buttons[next].focus()}})});root.append(controls,panel);show(data.defaultIndex||0)
}
function quiz(root,data){
 const form=el('form');const group=el('fieldset');group.append(el('legend',data.question));const options=el('div',null,{class:'quiz-options'});
 data.options.forEach((o,i)=>{const label=el('label',null,{class:'quiz-option'}),input=el('input',null,{type:'radio',name:'answer',value:String(i),required:''});label.append(input,el('span',o.label));options.append(label)});group.append(options);const submit=el('button','Check my answer',{type:'submit'});const feedback=el('div',null,{class:'feedback hidden','aria-live':'polite'});form.append(group,submit);form.addEventListener('submit',e=>{e.preventDefault();const chosen=Number(new FormData(form).get('answer'));feedback.classList.remove('hidden');feedback.replaceChildren(el('strong',data.options[chosen].correct?'That matches this example.':'Here is the distinction.'),paragraph(data.options[chosen].feedback));});root.append(form,feedback)
}
function decoys(root,data){
 const form=el('form');const intro=paragraph(data.question);const table=el('table');const caption=el('caption','Practice scenario — invented for this guide');table.append(caption);const head=el('thead'),hr=el('tr');['Example item','Looks like a decoy','I would investigate'].forEach(s=>hr.append(el('th',s,{scope:'col'})));head.append(hr);table.append(head);const body=el('tbody');
 data.items.forEach((item,i)=>{const row=el('tr');row.append(el('th',item.label,{scope:'row'}));['decoy','investigate'].forEach(k=>{const cell=el('td');cell.append(el('input',null,{type:'checkbox',name:`${k}-${i}`,'aria-label':`${k==='decoy'?'Mark as decoy':'Investigate'}: ${item.label}`}));row.append(cell)});body.append(row)});table.append(body);const wrap=el('div',null,{class:'table-scroll',tabindex:'0',role:'region','aria-label':'Decoy exercise'});wrap.append(table);const submit=el('button','Explain my choices',{type:'submit'}),reset=el('button','Reset',{type:'reset'}),buttons=el('div',null,{class:'controls'});buttons.append(submit,reset);const feedback=el('div',null,{class:'feedback hidden','aria-live':'polite'});form.append(intro,wrap,buttons);form.addEventListener('submit',e=>{e.preventDefault();const values=new FormData(form);feedback.replaceChildren();data.items.forEach((item,i)=>{const d=values.has(`decoy-${i}`),investigate=values.has(`investigate-${i}`);feedback.append(el('strong',item.label),paragraph(item.explanation),paragraph(d&&investigate?'You both marked this as a decoy and chose to investigate it. Recognizing a warning and changing a choice are separate behaviors.':investigate?'You chose to investigate this item. This exercise records a choice, not a real attack.':d?'You marked this item as a possible decoy. That is a judgment within this invented example.':'You left this item unselected.'))});feedback.classList.remove('hidden')});form.addEventListener('reset',()=>{feedback.classList.add('hidden');feedback.replaceChildren()});root.append(form,feedback)
}
function calculator(root,data){
 const grid=el('div',null,{class:'form-grid'}),modelLabel=el('label',null,{class:'field'});modelLabel.append(el('span','Model and provider'));const select=el('select',null);data.models.forEach((m,i)=>select.append(el('option',m.name,{value:String(i)})));modelLabel.append(select);grid.append(modelLabel)
 const values={turns:8,contextK:24,outputK:2};const inputs={};
 [['turns','Steps in the task',2,24,1],['contextK','Repeated background text (thousand tokens)',4,260,4],['outputK','New answer at each step (thousand tokens)',1,12,1]].forEach(([key,label,min,max,step])=>{const field=el('label',null,{class:'field'}),output=el('output',String(values[key]));field.append(el('span',label),output);const input=el('input',null,{type:'range',min,max,step,value:values[key],'aria-label':label});input.addEventListener('input',()=>{values[key]=Number(input.value);output.textContent=input.value;update()});inputs[key]=input;field.append(input);grid.append(field)})
 const receipt=el('div',null,{class:'receipt','aria-live':'polite'}),note=el('div',null,{class:'calculation-note'});root.append(grid,receipt,note);select.addEventListener('change',update)
 function update(){const model=data.models[Number(select.value)],r=estimateCost(values,model);receipt.replaceChildren();note.replaceChildren();if(!r.valid){note.append(paragraph(r.reason));return}
 for(const [label,amount] of [['Without cached text',r.uncached],['With eligible reused text cached',r.cached]]){const box=el('div');box.append(el('span',label),el('strong',money(amount)));receipt.append(box)}
 note.append(paragraph(`${number(r.inputTokens)} input tokens and ${number(r.outputTokens)} output tokens across ${values.turns} steps. The busiest step contains ${number(r.maxInputTokens)} input tokens.`));note.append(paragraph(`${number(r.cacheReadTokens)} tokens are priced as cache reads. ${number(r.cacheWriteTokens)} are fresh input tokens, including cache writes where applicable. The first input is not a cache hit.`));note.append(paragraph(model.notes||''));if(r.longSteps)note.append(paragraph(`${r.longSteps} steps use the provider’s higher long-context rates.`));note.append(paragraph(data.assumptions));const source=el('a','Check this provider’s current pricing',{href:model.source});note.append(source)
 }
 update()
}
function comparison(root,data){
 const tools=el('div',null,{class:'board-tools'}),label=el('label','Sort by '),sort=el('select',null,{class:'board-select'});[['task','Illustrative task cost'],['input','Input text price'],['output','Output text price'],['name','Model name']].forEach(([value,text])=>sort.append(el('option',text,{value})));label.append(sort);const only=el('label'),checkbox=el('input',null,{type:'checkbox'});only.append(checkbox,document.createTextNode(' Downloadable weights only'));tools.append(label,only);const tableWrap=el('div',null,{class:'table-scroll',tabindex:'0',role:'region','aria-label':'Model pricing comparison'}),chart=el('div',null,{class:'cost-chart'});root.append(tools,paragraph('All amounts are US dollars. Input and output rates are per one million text tokens. Task cost uses the same illustrative eight-step task for every model; it is not a quality score.'),tableWrap,chart);sort.addEventListener('change',update);checkbox.addEventListener('change',update)
 function update(){const rows=data.models.filter(m=>!checkbox.checked||m.openWeights).map(m=>({...m,task:estimateCost({turns:8,contextK:24,outputK:2},m).uncached}));rows.sort((a,b)=>sort.value==='name'?a.name.localeCompare(b.name):a[sort.value]-b[sort.value]);const table=el('table'),head=el('thead'),tr=el('tr');['Model','Input','Output','Task cost','Downloadable weights'].forEach(s=>tr.append(el('th',s,{scope:'col'})));head.append(tr);table.append(head);const body=el('tbody');rows.forEach(m=>{const row=el('tr'),name=el('th',null,{scope:'row'});name.append(el('a',m.name,{href:m.source}));row.append(name,...[money(m.input),money(m.output),money(m.task),m.openWeights?'Yes; check license':'No'].map(s=>el('td',s)));body.append(row)});table.append(body);tableWrap.replaceChildren(table);chart.replaceChildren(el('h4','Cost of the same example task'));if(!rows.length){chart.append(paragraph('No verified downloadable models in this snapshot.'));return}const max=Math.max(...rows.map(r=>r.task));rows.forEach(m=>{const row=el('div',null,{class:'chart-row'}),track=el('div'),bar=el('div',null,{class:'chart-bar','aria-hidden':'true'});bar.style.width=`${max?m.task/max*100:0}%`;track.append(bar);row.append(el('span',m.name),track,el('span',money(m.task)));chart.append(row)})}
 update()
}
for(const wrapper of document.querySelectorAll('[data-interactive]')){
 const data=JSON.parse(wrapper.querySelector('.interactive-data').textContent),root=wrapper.querySelector('.interactive-body'),kind=wrapper.dataset.interactive;
 if(kind==='lifecycle'||kind==='openness')tabs(root,data,kind);else if(kind==='quiz')quiz(root,data);else if(kind==='decoys')decoys(root,data);else if(kind==='cost')calculator(root,data);else if(kind==='comparison')comparison(root,data)
}
