export const projects = [
  {
    number: '01',
    title: 'AI Agent Architecture',
    type: 'AI systems research',
    description: 'An agent is loops, tools, context, and permissions, not a model by itself. This visual guide walks those layers, including evaluation and safety.',
    tools: ['Agent Loops', 'Graph Workflows', 'Evaluation', 'Safety'],
    status: 'Visual research',
    url: 'https://jbm-agent-architecture.netlify.app',
  },
  {
    number: '02',
    title: 'AI Agents Escaping Sandboxes',
    type: 'AI security review',
    description: 'Agents leave intended boundaries when tools and permissions are the real attack surface. Trusting model behavior is not a control.',
    tools: ['AI Security', 'Sandboxing', 'Threat Modeling'],
    status: 'Field note',
    url: 'https://jbm-agent-sandbox-review.netlify.app',
  },
  {
    number: '03',
    title: 'Open, But How Open?',
    type: 'AI ecosystem research',
    description: 'Open-weight, open-source, and closed are different. The labels get mixed on purpose and by accident.',
    tools: ['Open Weights', 'Open Source AI', 'Model Policy', 'AI Infrastructure'],
    status: 'Visual explainer',
    url: 'https://jbm-open-models-explained.netlify.app',
  },
  {
    number: '04',
    title: 'The Hidden Cost of AI Agents',
    type: 'Agent economics research',
    description: 'The harness around the model often spends more tokens than the prompt. Loops, context, tools, and caching set the real bill.',
    tools: ['Agent Harnesses', 'Token Economics', 'Prompt Caching', 'Context Engineering'],
    status: 'Interactive explainer',
    url: 'https://jbm-harness-economics.netlify.app',
  },
  {
    number: '05',
    title: 'Secure SDLC: STRIDE, PASTA & SSDF',
    type: 'Software security research',
    description: 'STRIDE, PASTA, and NIST SSDF make software risk visible before release. Security has to enter the lifecycle, not the postmortem.',
    tools: ['Secure SDLC', 'STRIDE', 'PASTA', 'NIST SSDF'],
    status: 'Visual research',
    url: 'https://jbm-secure-sdlc.netlify.app',
  },
  {
    number: '06',
    title: 'Hacking a Satellite—Safely Explained',
    type: 'Space systems security',
    description: 'Satellite security is ground stations, radio links, updates, and credentials, not movie hacking.',
    tools: ['Space Systems', 'Threat Modeling', 'NIST'],
    status: 'Visual investigation',
    url: 'https://jbm-satellite-cyber.netlify.app',
  },
  {
    number: '07',
    title: 'Honeyquest for LLMs',
    type: 'AI security review',
    description: 'Human cyber-deception assumptions do not transfer to LLM attackers. They take bait more, do not get diverted, and still exploit traps they named.',
    tools: ['AI Security', 'Cyber Deception', 'LLM Evaluation'],
    status: 'Visual research',
    url: 'https://jesusmbm.github.io/jbusty.github.io/honeyquest/',
  },
]
