export const projects = [
  {
    number: '01',
    title: 'How AI agents work',
    type: 'AI systems research',
    description: 'Follow a task from the first instruction to an action, a result, and a check. Learn where human approval and safety limits belong.',
    tools: ['Agent Loops', 'Graph Workflows', 'Evaluation', 'Safety'],
    status: 'Visual research',
    url: `${import.meta.env.BASE_URL}research/jbm-agent-architecture/`,
  },
  {
    number: '02',
    title: 'When AI agents cross security boundaries',
    type: 'AI security review',
    description: 'What recent incidents tell us about access limits, testing environments, and the difference between a reported event and a proven finding.',
    tools: ['AI Security', 'Sandboxing', 'Threat Modeling'],
    status: 'Field note',
    url: `${import.meta.env.BASE_URL}research/jbm-agent-sandbox-review/`,
  },
  {
    number: '03',
    title: 'What “open” means for an AI model',
    type: 'AI ecosystem research',
    description: 'Understand what you can download, change, and use—and why the specific license matters.',
    tools: ['Open Weights', 'Open Source AI', 'Model Policy', 'AI Infrastructure'],
    status: 'Visual explainer',
    url: `${import.meta.env.BASE_URL}research/jbm-open-models-explained/`,
  },
  {
    number: '04',
    title: 'What an AI agent actually costs',
    type: 'Agent economics research',
    description: 'Try a cost calculator, compare dated provider prices, and see why repeated steps and reused text change the bill.',
    tools: ['Agent Harnesses', 'Token Economics', 'Prompt Caching', 'Context Engineering'],
    status: 'Interactive explainer',
    url: `${import.meta.env.BASE_URL}research/jbm-harness-economics/`,
  },
  {
    number: '05',
    title: 'How teams build safer software',
    type: 'Software security research',
    description: 'An everyday guide to checking risks from planning through maintenance, with three common approaches explained.',
    tools: ['Secure SDLC', 'STRIDE', 'PASTA', 'NIST SSDF'],
    status: 'Visual research',
    url: `${import.meta.env.BASE_URL}research/jbm-secure-sdlc/`,
  },
  {
    number: '06',
    title: 'How satellite systems stay secure',
    type: 'Space systems security',
    description: 'See how satellites, ground stations, radio links, and user devices work together—and what each needs to stay secure.',
    tools: ['Space Systems', 'Threat Modeling', 'NIST'],
    status: 'Visual investigation',
    url: `${import.meta.env.BASE_URL}research/jbm-satellite-cyber/`,
  },
  {
    number: '07',
    title: 'Can decoys mislead AI attackers?',
    type: 'AI security review',
    description: 'What one study found when AI models were asked to choose between simulated files, links, and decoys—and what it cannot prove.',
    tools: ['AI Security', 'Cyber Deception', 'LLM Evaluation'],
    status: 'Visual research',
    url: 'https://jesusmbm.github.io/jbusty.github.io/honeyquest/',
  },
]
